# Generated by Django 4.0.3 on 2022-03-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='topology_labels',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
