# Generated by Django 4.0.2 on 2022-03-15 21:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_job_title_user_role_user_topology_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topology_labels',
            field=models.JSONField(default=user.models.default_dict),
        ),
    ]
