# Generated by Django 4.0.2 on 2022-04-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='topology_labels',
        ),
        migrations.AddField(
            model_name='user',
            name='topology_labels',
            field=models.ManyToManyField(to='user.Label'),
        ),
    ]
