# Generated by Django 4.0.2 on 2022-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_topology_labels_user_topology_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topology_labels',
            field=models.ManyToManyField(blank=True, to='user.Label'),
        ),
    ]
