name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:  
      working-directory: ./Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          #build: npm run build
          start: npm start
          #run: npx cypress info
          run: npx cypress run --record --key f906080d-d028-410d-8e6f-9ae901a86e1e
          wait-on: http://localhost:3000
          working-directory: ${{env.working-directory}}
      
